[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bf_interpreter"
path = "src/main_interpreter.rs"

[[bin]]
name = "bf_ir"
path = "src/main_ir.rs"

[dependencies]
